GET http://localhost:3003/api/blogs/

###

POST http://localhost:3003/api/blogs/
content-Type: application/json

{
  "title": "Node",
  "author": "Mark Zukenberg",
  "url": "",
  "likes": 0
}

###

PUT http://localhost:3003/api/blogs/6417aa740267d13952260702
content-Type: application/json

{
  "title": "HTML VS CSS",
  "author": "Gerardo da Cousino",
  "url": "http",
  "likes": 2,
  "user": "643ccad1fbea2971c91c27ec"
}
###

POST http://localhost:3003/api/blogs/
content-Type: application/json

{
  "title": "CSS forever",
  "author": "Gigi Kiki",
  "url": "http",
  "likes": 2,
  "userId": "643cce2e6f8afc187dbe624a"
}
   