GET http://localhost:3003/api/blogs/

###

POST http://localhost:3003/api/blogs/
content-Type: application/json

{
  "title": "Node",
  "author": "Mark Zukenberg",
  "url": "",
  "likes": 0
}

###

PUT http://localhost:3003/api/blogs/644087e9ee408b3a15618500
content-Type: application/json

{
  "title": "HTML VS CSS",
  "author": "Gerardo da Cousino",
  "url": "http",
  "likes": 2,
  "user": "643ccad1fbea2971c91c27ec"
}
###

POST http://localhost:3003/api/blogs/
content-Type: application/json
# Authorization: Bearer 
{
  "title": "What's going on in React",
  "author": "Mr Code",
  "url": "http",
  "likes": 2,

}
   