
POST http://localhost:3006/api/login/
content-Type: application/json

{
    "username": "root",
    "password": "salainen"
}

###


POST http://localhost:3006/api/notes/
content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjY0MTdmMjJjNGRiZDY1Mzc3NDE0MzRmYiIsImlhdCI6MTY3OTQ1NDA5MX0._Al-mVAN5mw-hs-xFMs9OuTp6Lq1tkPzS7BaUEyAJeg

{
    "content": "Authorization isnt the funiest thing to do",
    "important": true
}
