
GET http://localhost:3003/api/users/


###
POST http://localhost:3003/api/users/
content-Type: application/json

{
    "username": "root",
    "name": "Superuser",
    "password": "rootuser"
}
###


POST http://localhost:3003/api/login/
content-Type: application/json

{
    "username": "root",
    "password": "rootuser"
}

###


POST http://localhost:3003/api/blogs/
content-Type: application/json
# Authorization: Bearer 

{
    "title": "java is harder than python",
  "author": "Kurz Markenberg",
  "url": "",
  "likes": 3
}
