
GET http://localhost:3003/api/users/


###
POST http://localhost:3003/api/users/
content-Type: application/json

{
    "username": "root",
    "name": "Superuser",
    "password": "rootuser"
}
###


POST http://localhost:3003/api/login/
content-Type: application/json

{
    "username": "root",
    "password": "rootuser"
}

###


POST http://localhost:3003/api/blogs/
content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjY0M2NjYWQxZmJlYTI5NzFjOTFjMjdlYyIsImlhdCI6MTY4MTc5NTQ1M30.BI87OQ4LLMCieUMKCRnl-Y1Zt2buYY-Fxx7Ep3s_ov8

{
    "title": "java is harder than python",
  "author": "Kurz Markenberg",
  "url": "",
  "likes": 3
}
